config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'

  namespace :assets do
    resources :jobs, only: [:index, :create, :show, :update]
  end

  namespace :customers do
    resources :jobs, only: [:index, :show, :update]
  end

  resources :assets, only: [:index, :show] do
    resources :jobs, only: [:create]
  end

  resources :jobs, only: [:delete, :create] do
    member do
      get 'done'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :asset, class_name: 'User'
  validates :target_name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  validates :username, presence: true
  validate :has_weapon_if_is_asset

  scope :assets, -> { where(asset_status: true) }

  has_attachment :picture


  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  def show
    @asset = User.asset.find(params[:id])
    @alert_message = "You are viewing #{@asset.username}"
  end


  def has_weapon_if_is_asset
    if asset_status and weapons.blank?
      errors.add(:weapons, "You must have a weapon if you are an asset")
    end
  end

  def asset?
    asset_status
  end

  def customer?
    not asset_status
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :asset_status, :weapons, :picture])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :asset_status, :weapons, :picture])
  end


  def selection_params
    params.require(:selection).permit(:city, :weapon)
  end

end

app/controllers/assets/jobs_controller.rb
class Assets::JobsController < ApplicationController

  before_action :find_job, only: [:show, :update]

  def index
  end

  def show

#    @job   = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.asset = @asset
    @job.user = current_user
    if @job.save
      redirect_to customers_job_path(@job)
    else
      render "assets/show"
    end
  end

  def update

    @job.update(job_params)
    redirect_to assets_jobs_path
  end

  private

  def find_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:review, :target_name, :description, :address, :deadline)
  end

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @assets = User.assets.where.not(latitude: nil, longitude: nil)

    if params[:selection]
      if params[:selection][:city].present?
        @assets = @assets.near(params[:selection][:city], 100)
      end
      if params[:selection][:weapons].present?
        @assets = @assets.where(weapons: params[:selection][:weapons])
      end
      # if params[:selection][:city].present? || params[:selection][:weapons].present?
      #   @assets = @assets.where(weapons: params[:selection][:weapons],"city LIKE ?","%#{params[:selection][:city].capitalize}%")
      # end
    end
    # @asset_coord = []
    # User.assets.each do |killer|
    #   @asset_coord << killer.near([killer.latitude][killer.longitude], 10)
    # end
    @hash = Gmaps4rails.build_markers(@assets) do |asset, marker|
      marker.lat asset.latitude
      marker.lng asset.longitude
      # marker.infowindow render_to_string(partial: "/assets/map_box", locals: { asset: asset })
    end
  end

  def show
    @asset = User.assets.find(params[:id])
    @asset_coordinates = { lat: @asset.latitude, lng: @asset.longitude }
    @hash = Gmaps4rails.build_markers(@assets) do |asset, marker|
      marker.lat asset.latitude
      marker.lng asset.longitude
      marker.infowindow render_to_string(partial: "/assets/map_box", locals: { asset: asset })
    end
    @job = Job.new
    @asset_jobs = @asset.jobs
  end
end

app/controllers/customers/jobs_controller.rb
class Customers::JobsController < ApplicationController

  before_action :find_job, only: [:show, :update]

  def index
  end

  def show
    @jobs = Job.where(user: current_user)
    job_count = @jobs.size
  end

  def update
    @job.update(job_params)
    redirect_to asset_path(@job.user_id)
  end

  private

  def find_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:review)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_asset, only: [:create]
	before_action :set_job, only: [:destroy, :done]

	def index
		@jobs = current_user.jobs
	end

	def show
	end

	def create
		raise
		@job = Job.new(job_params)
		@job.asset = @asset
    @job.user = current_user
    raise
    if @job.save
			redirect_to customers_job_path(@job)
		else
			render "assets/show"
    end
	end

	def destroy
		@job.destroy
		redirect_to jobs_path(@user)
	end

  def done
    raise "job #{@job.id} is done"
  end

	private

	def set_job
		@job = Job.find(params[:id])
	end

	def set_asset
    @asset = User.find(params[:asset_id])
  end

	def job_params
		params.require(:job).permit(:id, :target_name, :description, :address, :deadline)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]


  def home
    @weapons = []
    User.all.each do |killer|
      @weapons << killer.weapons
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/assets/index.html.erb
<!-- Banner Start -->
<section id="global-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1>Just some of our best killers.</h1>
                    <p>Choose from the best. Check out their latest piece of work.</p>
                </div>
            </div>
         </div>
    </div>
</section>
<div class="container">
    <div class="row">
     <div class="col-md-12">
            <% @assets.each do |asset| %>
        <div class="col-md-3 col-sm-6">
              <div class="card-container">
                <div class="card">
                    <div class="front">
                        <div class="cover">
                          <div class="card-header" style="background: rgba(189,189,189,1);">
                          </div>
                        </div>
                        <div class="user">
                            <%= link_to asset_path(asset) do %>
                              <%= cl_image_tag asset.picture.path, class: 'img-circle' %>
                            <% end %>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name"><%= asset.username %></h3>
                                <p class="profession">Hitman</p>
                                <p class="text-center"><%= asset.profile_description %></p>
                            </div>
                        </div>
                    </div> <!-- end front panel -->
                <%= link_to asset_path(asset) do %>
                    <div class="back">
                        <div class="header">
                            <h5 class="motto"><%= asset.weapons %></h5>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h4 class="text-center"><%= asset.city %></h4>
                                <p class="text-center">Web design, Adobe Photoshop, HTML5, CSS3, Corel and many others...</p>
                                <div class="stats-container">
                                    <div class="stats">
                                        <h4>235</h4>
                                        <p>
                                            XP
                                        </p>
                                    </div>
                                    <div class="stats">
                                        <h4><%= asset.number_of_kills %></h4>
                                        <p>
                                            Number of Kills
                                        </p>
                                    </div>
                                    <div class="stats">
                                        <h4>35</h4>
                                        <p>
                                            Rating
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <div class="social-links text-center">
                                <a href="http://coincoin.pan" class="facebook"><i class="fa fa-facebook fa-fw"></i></a>
                                <a href="http://coincoin.pan" class="google"><i class="fa fa-google-plus fa-fw"></i></a>
                                <a href="http://coincoin.pan" class="twitter"><i class="fa fa-twitter fa-fw"></i></a>
                            </div>
                        </div>
                    </div> <!-- end back panel -->
                </div> <!-- end card -->
                <% end %>
              </div> <!-- end card-container -->
            </div> <!-- end col md 4 -->
        <% end %>
      </div> <!-- end col sm 10 -->
    </div> <!-- end row -->
  </div> <!-- end container -->
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<!-- <div id="map" style="width: 100%; height: 500px;"></div>

    <%# content_for(:after_js) do %>

        <script>
        $(document).ready(function() {

            var styles = [{"featureType":"administrative","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"administrative.province","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"landscape","elementType":"all","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","elementType":"all","stylers":[{"saturation":-100},{"lightness":"50"},{"visibility":"simplified"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"all","stylers":[{"lightness":"30"}]},{"featureType":"road.local","elementType":"all","stylers":[{"lightness":"40"}]},{"featureType":"transit","elementType":"all","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]},{"featureType":"water","elementType":"labels","stylers":[{"lightness":-25},{"saturation":-100}]}]

            var handler = Gmaps.build('Google');
            handler.buildMap({
              provider: {
                styles: styles
              },
              internal: { id: 'map' }}, function() {
                markers = handler.addMarkers([<%#= raw @hash.to_json %>]);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
            });
          </script>

    <%# end %> -->

    <div id="map" style="width: 100%; height: 600px;"></div>

    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        $(document).ready(function() {
          var handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
        });
      <% end %>
    <% end %>



<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

app/views/assets/jobs/index.html.erb
<h1>hitman jobs</h1>

<% byebug %>
<% @job = Job.all %>
<% @user = User.new %>

<div class="wrapper" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 30%);">
  <h4 class="text-left">Asset Jobs Review</h4>
    <ul>
      <% @job.each do |job| %>
      <%    @user = User.find(job.asset_id) %>
        <li>
          <%= @user.username %>
          <%= "======" %>
          <%= job.review %>
        </li>
      <% end %>
    </ul>
</div>

app/views/assets/jobs/show.html.erb
<h3 class="text-center">Asset Job Review</h3>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <%= simple_form_for @job, url:  assets_job_path(@job) do |f| %>
        <%= f.input :review, placeholder: "Please Enter your review" %>
        <%= f.submit "Update Review", class: "btn btn-success"%>
      <% end %>
    </div>
  </div>
</div>

app/views/assets/show.html.erb
<!-- Slider Start -->
        <section id="global-header">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="block">
                  <h1>Book a job with me</h1>
                  <p>Don’t just hesitate, go for it!. Check out some of my latest work.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <!-- contact form start -->
        <section id="contact-form">
          <div class="container">
            <div class="row">
            <div id="contact-box" class="row">
              <div class="col-md-6 col-sm-12">
                <div class="block">
                  <h2>A little bit more about me</h2>
                  <ul class="address-block">
                    <li>
                      <i class="Username"></i>Username : <%= @asset.username %>
                    </li>
                     <li>
                      <i class="Description"></i>Description : <%= @asset.profile_description %>
                    </li>
                    <li>
                      <i class="Weapons"></i>Weapons : <%= @asset.weapons %>
                    </li>
                    <li>
                      <i class="City"></i>City : <%= @asset.city %>
                    </li>
                    <li>
                      <i class="Kills"></i>Number of kills : <%= @asset.number_of_kills %>
                    </li>
                  </ul>
                  <ul class="social-icons">
                    <li><i class="fa fa-google"></i></li>
                    <li><i class="fa fa-linkedin"></i></li>
                    <li><i class="fa fa-pinterest"></i></li>
                    <li><i class="fa fa-dribbble"></i></li>
                    <li><i class="fa fa-behance"></i></li>
                    <li><i class="fa fa-twitter"></i></li>
                    <li><i class="fa fa-facebook"></i></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-sm-12">
                <div class="block">
                  <h2>Find me on Google Map</h2>
                    <div class="google-map">
                      <div id="map"></div>
                    </div>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="blocktest">
                   <%= render "jobs/form" %>
                </div>
              </div>
            </div>
            </div>
          </div>
        </section>
        <!-- Call to action Start -->
        <section id="call-to-action">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="block">
                  <h2>We simply kill people.</h2>
                  <p>Read more about what we do and our philosophy of getting the job done. Judge for yourself! The work and results we’ve achieved for our clients, and meet our highly experienced Team who just love to kill.</p>
                  <a class="btn btn-default btn-call-to-action" href="#" >Send us a review</a>
                </div>
              </div>
            </div>
          </div>
        </section>
    <% content_for(:after_js) do %>
      <script>
        $(document).ready(function() {
          var styles = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}]
          var handler = Gmaps.build('Google');
          handler.buildMap({
            provider: {
              styles: styles
            },
            internal: { id: 'map' }
            }, function() {
            markers = handler.addMarkers([<%= raw @asset_coordinates.to_json %>]);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
        });
      </script>
    <% end %>
  </div>
</div>

app/views/customers/jobs/index.html.erb
<h2>customers ordered jobs</h2>

app/views/customers/jobs/show.html.erb
<h3 class="text-center">Customer Job Review</h3>

<%= render 'shared/list' %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @job, url:  customers_job_path(@job) do |f| %>
        <%= f.input :review, placeholder: "Please Enter your review" %>
        <%= f.submit "Update Review", class: "btn btn-success"%>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= simple_form_for @job, url: assets_jobs_path do |f| %>
  <%= f.input :target_name %>
  <%= f.input :deadline %>
  <%= f.input :address %> 
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/_review.html.erb
<%= simple_form_for(@job) do |f| %>
    <%= f.input :name, placeholder: "Review" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/jobs/create.html.erb
<h1>Pages#Create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/index.html.erb
<%= @jobs.inspect %>

app/views/jobs/show.html.erb
<h1>Pages#Show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Killn'B</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>

  </head>
  <body>
    <%= render 'shared/navbar' unless controller_name == "pages" && action_name == "home"  %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' unless controller_name == "pages" && action_name == "home" %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.6) 80%), url(<%= image_path 'jockybw.jpg'%>);">
  <div class="banner-content">
    <h1><%= image_tag 'killnb.png'%></h1>
    <p>A Very cool Team of killers, A service useful, smart and easy</p>
    <div class="form-inline">
      <%= render 'shared/search_form' %>
    </div>
    <br>

    <%= link_to assets_path do %>
      <%= image_tag 'killme.png' %>
    <% end %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="footer-manu">
          <ul>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact us</a></li>
            <li><a href="#">How it works</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Terms</a></li>
          </ul>
        </div>
        <p>Copyright Design & Developed by L4T34m ! </a>. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_list.html.erb
<% @jobs.each do |job| %> 

<div class="product">
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'></div>
  </div>
  <img alt="kudoz" class="product-image hidden-xs"<%= image_tag "icon-dead.png" %>
  <div class='product-body'>

    <h5>Your target is : <%= job.target_name %></h5>
    <h5>Please kill you target before : <%= job.deadline %> to get paid.</h5>
    <h5>Your target address is : <%= job.address %></h5>
    <h5>Please find a small description for the job : <%= job.description %></h5>

  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li><a href=""><i class="fa fa-check-circle-o"></i></a></li>
    <li><a href=""><i class="fa fa-usd"></i></a></li>
    <li><a href=""><i class="fa fa-star"></i></a></li>
  </ul>
</div>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <i class="fa fa-home"></i>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search" style="font-size: 16px;"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- sign_up text link -->
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Don't click me..."), "http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=19040004", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= simple_form_for :selection, url: assets_path, method: :get do |f| %>
  <%= f.input :city, label: false, prompt: 'city?' %>
  <%= f.input :weapons, collection: @weapons, label: false, prompt: 'weapon ?' %>
  <%= f.button :submit %>
  <% end %>